// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UA.Action.Freedom.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ReceiversAPIFeature : object, Xunit.IClassFixture<ReceiversAPIFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Receivers API", @"    The deployed Freedom service exposes receivers at /receivers, and their Ukrainian
    delivery detail at /receivers/{ref}/detail.

    The split is the point. /receivers carries an opaque reference, an organisation and a
    region — the shape that may be printed on something crossing a border. The delivery
    address and contact are Ground Officer only, and every resolve is audited. A manifest
    listing precise delivery addresses is a targeting document.

    Three separate controls enforce that and these scenarios exercise the outermost one:
    the receivers:detail policy. Behind it sit a distinct database identity and a DENY on
    the sensitive schema, both covered by the integration tests.

    These scenarios run against the running containers (the edge on
    http://localhost:8080, Keycloak on http://localhost:8081) and skip themselves
    when that stack is not up.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Receivers.feature"
#line hidden
        
        public ReceiversAPIFeature(ReceiversAPIFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 18
#line hidden
#line 19
    await testRunner.GivenAsync("the Freedom API exposes \"/receivers\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Receivers.feature.ndjson", 13);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Reading receivers requires a token")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "Reading receivers requires a token")]
        public async global::System.Threading.Tasks.Task ReadingReceiversRequiresAToken()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reading receivers requires a token", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.WhenAsync("I GET \"/receivers\" without a token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("the response status is 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A ground officer registers a receiving organisation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A ground officer registers a receiving organisation")]
        public async global::System.Threading.Tasks.Task AGroundOfficerRegistersAReceivingOrganisation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A ground officer registers a receiving organisation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
    await testRunner.AndAsync("the \"Location\" header names a new resource", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An operational role sees the region but never the address")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "An operational role sees the region but never the address")]
        public async global::System.Threading.Tasks.Task AnOperationalRoleSeesTheRegionButNeverTheAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An operational role sees the region but never the address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
    await testRunner.WhenAsync("I PUT \"/receivers/{id}/detail\" with body:", "{ \"contactName\": \"Olena Kovalenko\", \"contactPhone\": \"+380501234567\", \"addressLine" +
                        "1\": \"12 Vulytsia Sumska\", \"city\": \"Kharkiv\", \"postCode\": \"61002\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the response status is 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.GivenAsync("I am authenticated as \"operator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("I GET \"/receivers/{id}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
    await testRunner.AndAsync("the response body field \"region\" is \"Kharkiv oblast\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.AndAsync("the response body does not mention \"Vulytsia Sumska\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("the response body does not mention \"Olena Kovalenko\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.AndAsync("the response body does not mention \"+380501234567\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A dispatcher is refused a delivery address")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A dispatcher is refused a delivery address")]
        public async global::System.Threading.Tasks.Task ADispatcherIsRefusedADeliveryAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A dispatcher is refused a delivery address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 55
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 61
    await testRunner.GivenAsync("I am authenticated as \"operator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync("I GET \"/receivers/{id}/detail\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An administrator is refused a delivery address too")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "An administrator is refused a delivery address too")]
        public async global::System.Threading.Tasks.Task AnAdministratorIsRefusedADeliveryAddressToo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An administrator is refused a delivery address too", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 66
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 67
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.GivenAsync("I am authenticated as \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
    await testRunner.WhenAsync("I GET \"/receivers/{id}/detail\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A ground officer records and resolves a delivery address")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A ground officer records and resolves a delivery address")]
        public async global::System.Threading.Tasks.Task AGroundOfficerRecordsAndResolvesADeliveryAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A ground officer records and resolves a delivery address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 77
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 83
    await testRunner.WhenAsync("I PUT \"/receivers/{id}/detail\" with body:", "{ \"contactName\": \"Olena Kovalenko\", \"contactPhone\": \"+380501234567\", \"addressLine" +
                        "1\": \"12 Vulytsia Sumska\", \"city\": \"Kharkiv\", \"postCode\": \"61002\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("the response status is 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
    await testRunner.WhenAsync("I GET \"/receivers/{id}/detail?reason=Delivery%20scheduled%2012%20Sept\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
    await testRunner.AndAsync("the response body field \"addressLine1\" is \"12 Vulytsia Sumska\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.AndAsync("the response body field \"city\" is \"Kharkiv\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A dispatcher may not record a delivery address")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A dispatcher may not record a delivery address")]
        public async global::System.Threading.Tasks.Task ADispatcherMayNotRecordADeliveryAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A dispatcher may not record a delivery address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 93
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 94
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
    await testRunner.GivenAsync("I am authenticated as \"operator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
    await testRunner.WhenAsync("I PUT \"/receivers/{id}/detail\" with body:", "{ \"contactName\": \"Olena Kovalenko\", \"contactPhone\": \"+380501234567\", \"addressLine" +
                        "1\": \"12 Vulytsia Sumska\", \"city\": \"Kharkiv\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A rejected delivery address is never echoed back")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A rejected delivery address is never echoed back")]
        public async global::System.Threading.Tasks.Task ARejectedDeliveryAddressIsNeverEchoedBack()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A rejected delivery address is never echoed back", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 107
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 108
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 114
    await testRunner.WhenAsync("I PUT \"/receivers/{id}/detail\" with body:", "{ \"contactName\": \"\", \"contactPhone\": \"+380501234567\", \"addressLine1\": \"12 Vulytsi" +
                        "a Sumska\", \"city\": \"Kharkiv\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
    await testRunner.ThenAsync("the response status is 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 119
    await testRunner.AndAsync("the response body does not mention \"Vulytsia Sumska\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.AndAsync("the response body does not mention \"+380501234567\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A receiver with no delivery address recorded is a 404 for the ground officer")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A receiver with no delivery address recorded is a 404 for the ground officer")]
        public async global::System.Threading.Tasks.Task AReceiverWithNoDeliveryAddressRecordedIsA404ForTheGroundOfficer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A receiver with no delivery address recorded is a 404 for the ground officer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 122
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 123
    await testRunner.GivenAsync("I am authenticated as \"groundofficer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 124
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Kharkiv Regional Hospital\", \"region\": \"Kharkiv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
    await testRunner.ThenAsync("the response status is 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 129
    await testRunner.WhenAsync("I GET \"/receivers/{id}/detail\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
    await testRunner.ThenAsync("the response status is 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A loader may not register a receiver")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "A loader may not register a receiver")]
        public async global::System.Threading.Tasks.Task ALoaderMayNotRegisterAReceiver()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A loader may not register a receiver", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 132
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 133
    await testRunner.GivenAsync("I am authenticated as \"operator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 134
    await testRunner.WhenAsync("I POST \"/receivers\" with body:", "{ \"organisation\": \"Somewhere Else\", \"region\": \"Lviv oblast\" }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 138
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Fetching an unknown receiver is a 404")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Receivers API")]
        [global::Xunit.TraitAttribute("Description", "Fetching an unknown receiver is a 404")]
        public async global::System.Threading.Tasks.Task FetchingAnUnknownReceiverIsA404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fetching an unknown receiver is a 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 140
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await this.FeatureBackgroundAsync();
#line hidden
#line 141
    await testRunner.GivenAsync("I am authenticated as \"operator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 142
    await testRunner.WhenAsync("I GET \"/receivers/b3f1c4d2-5a6e-4f70-8901-2c3d4e5f6a7b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 143
    await testRunner.ThenAsync("the response status is 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ReceiversAPIFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await ReceiversAPIFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
