@startuml Containers | UA Action Freedom

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist

!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml

!includeurl AzurePuml/Databases/AzureRedisCache.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Databases/AzureSqlDatabase.puml

!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Compute/AzureAppService.puml

!includeurl AzurePuml/Storage/AzureQueueStorage.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Storage/AzureStorageContainer.puml

!includeurl AzurePuml/Identity/AzureActiveDirectory.puml

!includeurl AzurePuml/Networking/AzureFrontDoor.puml

title Containers | UA Action Freedom

Person_Ext(donor, "Donor", "A person who donates to UA Action")
Person_Ext(guard, "Border Guard", "A person who represents a country border guards")
Person_Ext(driver, "Driver", "A person who drives vehicles")
Person_Ext(authority, "Authority", "A person who represents the local authorities")

System_Ext(ferry, "Ferry Website", "Booking of ferry tickets for vehicles")

Enterprise_Boundary(hmrc, "HMRC") {
    System_Ext(hmrc_goods_api, "Goods Movement System Haulier API", "API for the UK Government's Goods Movement System", $link="https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/goods-movement-system-haulier-api/1.0/oas/page")
    System_Ext(hmrc_notifications, "Push Pull Notifications API", "API for the UK Government's Notifications for asyncronous communication", $link="https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/push-pull-notifications-api/1.0/oas/page")

    hmrc_goods_api --> hmrc_notifications : Completes Goods Movement Requests
}

Enterprise_Boundary(ua_action, "UA Action") {

    
    Person(administrator, "Administrator", "A person who manages access and roles")
    Person(ground_officer, "Ground Officer", "A person who connects with local authorities to coordinate convoys and requests for aid")
    Person(purchaser, "Purchaser", "A person who manages procurement and supplies for convoys")    
    Person(loader, "Loader", "A person who loads cargo onto vehicles and verifies donations")
    Person(dispatcher, "Dispatcher", "A person who dispatches vehicles and manages paperwork for a convoy")

    System_Boundary(freedom, "Freedom") {

        AzureFrontDoor(front_door, "Front Door", "Azure Front Door", "Provides a secure entry point for Freedom users")

        AzureAppService(web_app, "Web Application", "ASP.NET Core MVC", "Allows users to manage convoys and donations")
        
        AzureAppService(api, "API", "ASP.NET Core Web API", "Provides access to Freedom data and functionality")
        AzureSqlDatabase(db, "Database", "Azure SQL Database", "Stores Freedom data")
        
        AzureQueueStorage(gmr_queue, "GMR Queue", "Azure Queue Storage", "Queue for Ground Movement Requests")
        AzureFunction(gmr_function, "GMR Function", "Azure Function", "Processes Ground Movement Requests from the queue")
         

        AzureBlobStorage(manifest_storage, "Manifest Storage", "Azure Blob Storage", "Stores cargo manifests for convoys")
        AzureBlobStorage(gmr_storage, "GMR Storage", "Azure Blob Storage", "Stores GMR for convoys")
        AzureBlobStorage(elo_storage, "ELO Storage", "Azure Blob Storage", "Stores ELO documents for convoys")
        
        front_door --> web_app : Routes requests
        web_app --> api : Uses
        api --> db : Reads from and writes
        
        api --> manifest_storage : Saves Cargo Manifest
        api --> elo_storage : Saves ELO Document

        gmr_queue --> gmr_function : Triggers
        gmr_function --> gmr_storage : Saves GMR Document        
    }

    AzureActiveDirectory(ad, "Azure Active Directory", "Identity Provider", "Provides authentication and authorization for Freedom users")

    System(website, "Public Website", "Public website for UA Action that provides information about the organization and its activities")
}

administrator --> ad : Manages Access and Roles

api --> gmr_queue : Sends Ground Movement Requests
api --> gmr_queue : Sends Refresh Requests for Ground Movement Requests

gmr_function --> api : Sends status updates of Ground Movement Requests

gmr_function --> hmrc_goods_api : Sends Goods Movement Requests
gmr_function --> hmrc_notifications : Receives status updates of Goods Movement Requests

donor --> website : Requests Donation Sheet
driver --> website : Requests to become a driver

freedom --> driver : Notified of Convoy Allocation

dispatcher <--> driver : Communicates convoy status

purchaser --> front_door : Manages Procurement

freedom --> loader : Recieves Cargo Manifest
loader --> front_door : Confirms Donations Contents

ground_officer --> front_door : Raises requests for aid
ground_officer <--> authority : Communicates with local authorities

dispatcher --> ferry : Books ferry tickets
dispatcher --> front_door : Updates convoy information

guard -> driver : Verifies convoy information

@enduml