<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>UA.Action.Freedom.CustomsWorker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.23.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HMRC.GVMS/HMRC.GVMS.csproj" />
    <ProjectReference Include="../HMRC.PushPullNotifications/HMRC.PushPullNotifications.csproj" />
  </ItemGroup>

</Project>
