# Pure(ish) helpers behind agent.ps1: slot -> ports, env/tfvars rendering, slot registry.
# Dot-source this file; nothing here touches git or docker, so Pester can test it directly.
# The bash twin (agent.sh) uses the same formula; tests/AgentSh.Tests.ps1 pins the two together.

Set-StrictMode -Version Latest

$script:PortOffsets = [ordered]@{
    EDGE_HTTP_PORT      = 0
    EDGE_HTTPS_PORT     = 1
    EDGE_DASHBOARD_PORT = 2
    KEYCLOAK_PORT       = 3
    WIREMOCK_PORT       = 4
    GRAFANA_PORT        = 5
    OTLP_GRPC_PORT      = 6
    OTLP_HTTP_PORT      = 7
    MAILPIT_UI_PORT     = 8
    MSSQL_PORT          = 9
    AZURITE_BLOB_PORT   = 10
    AZURITE_QUEUE_PORT  = 11
    AZURITE_TABLE_PORT  = 12
    VITE_PORT           = 13
}

# Slot 0 is the main checkout: today's ports, so CI and every existing doc stay true.
$script:MainPorts = [ordered]@{
    EDGE_HTTP_PORT      = 8080
    EDGE_HTTPS_PORT     = 8443
    EDGE_DASHBOARD_PORT = 8090
    KEYCLOAK_PORT       = 8081
    WIREMOCK_PORT       = 8082
    GRAFANA_PORT        = 3000
    OTLP_GRPC_PORT      = 4317
    OTLP_HTTP_PORT      = 4318
    MAILPIT_UI_PORT     = 8025
    MSSQL_PORT          = 1433
    AZURITE_BLOB_PORT   = 10000
    AZURITE_QUEUE_PORT  = 10001
    AZURITE_TABLE_PORT  = 10002
    VITE_PORT           = 5173
}

$script:MaxSlot = 9
$script:AgentKeycloakHeap = '-Xms128m -Xmx640m'
$script:AgentMssqlLimitMb = 1024
# What one capped stack (all containers, hot reload on) needs, measured. Used to warn, not to block.
$script:StackMemoryBytes = 3.5GB
$script:AzuriteKey = 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='

function Get-AgentPorts {
    param([Parameter(Mandatory)][int]$Slot)

    if ($Slot -lt 0 -or $Slot -gt $script:MaxSlot) {
        throw "Slot must be 0-$($script:MaxSlot), got $Slot."
    }

    $ports = [ordered]@{}
    foreach ($key in $script:PortOffsets.Keys) {
        $ports[$key] = if ($Slot -eq 0) { $script:MainPorts[$key] } else { 20000 + $Slot * 100 + $script:PortOffsets[$key] }
    }
    $ports
}

function Test-AgentName {
    param([string]$Name)
    $Name -cmatch '^[a-z][a-z0-9-]{0,19}$'
}

function Get-RegistrySlots {
    param([Parameter(Mandatory)]$Registry)

    $slots = @{}
    foreach ($name in $Registry.Keys) {
        $slots[$name] = [int]$Registry[$name].slot
    }
    $slots
}

function Select-AgentSlot {
    param(
        [Parameter(Mandatory)][hashtable]$Registry,
        [int]$Requested = 0
    )

    $taken = @{}
    foreach ($name in $Registry.Keys) { $taken[[int]$Registry[$name]] = $name }

    if ($Requested -gt 0) {
        if ($Requested -gt $script:MaxSlot) { throw "Slot must be 1-$($script:MaxSlot), got $Requested." }
        if ($taken.ContainsKey($Requested)) { throw "Slot $Requested is already used by '$($taken[$Requested])'." }
        return $Requested
    }

    foreach ($slot in 1..$script:MaxSlot) {
        if (-not $taken.ContainsKey($slot)) { return $slot }
    }
    throw "All $($script:MaxSlot) agent slots are in use (registry is full). Remove one with: agent.ps1 remove <name>"
}

function Get-ComposeFileLine {
    param([bool]$HotReload)
    if ($HotReload) { 'COMPOSE_FILE=docker-compose.yml:docker-compose.dev.yml' } else { 'COMPOSE_FILE=docker-compose.yml' }
}

function Set-EnvComposeFiles {
    param([Parameter(Mandatory)][AllowEmptyString()][string[]]$Lines, [Parameter(Mandatory)][bool]$HotReload)
    $Lines | ForEach-Object { if ($_ -like 'COMPOSE_FILE=*') { Get-ComposeFileLine -HotReload $HotReload } else { $_ } }
}

function New-AgentEnvContent {
    param(
        [Parameter(Mandatory)][AllowEmptyString()][string[]]$BaseLines,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][int]$Slot,
        [bool]$HotReload = $true
    )

    $ports = Get-AgentPorts -Slot $Slot
    $overridden = @('COMPOSE_PROJECT_NAME', 'FREEDOM_PREFIX', 'FREEDOM_IMAGE_TAG', 'KEYCLOAK_JAVA_HEAP', 'MSSQL_MEMORY_LIMIT_MB', 'COMPOSE_FILE', 'COMPOSE_PATH_SEPARATOR') + @($ports.Keys)

    $kept = $BaseLines | Where-Object {
        $key = ($_ -split '=', 2)[0].Trim()
        $overridden -notcontains $key
    }

    $generated = @(
        '',
        "# --- generated by agent.ps1 for '$Name' (slot $Slot); do not edit, re-run 'agent.ps1 new' ---",
        "COMPOSE_PROJECT_NAME=freedom-$Name",
        "FREEDOM_PREFIX=freedom-$Name",
        "FREEDOM_IMAGE_TAG=$Name",
        # So a bare `docker compose ps|down` in this worktree sees the same services agent.ps1 starts
        # (the Vite `web` service exists only in the dev file; without it `down` leaves it running).
        'COMPOSE_PATH_SEPARATOR=:',
        (Get-ComposeFileLine -HotReload $HotReload),
        # Keycloak and SQL Server are the two big ones; uncapped, three stacks exhaust a 16 GB Docker VM.
        "KEYCLOAK_JAVA_HEAP=`"$($script:AgentKeycloakHeap)`"",
        "MSSQL_MEMORY_LIMIT_MB=$($script:AgentMssqlLimitMb)"
    ) + @($ports.Keys | ForEach-Object { "$_=$($ports[$_])" })

    @($kept) + $generated
}

function New-AgentTfVars {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][int]$Slot
    )

    $p = Get-AgentPorts -Slot $Slot
    @(
        "# generated by agent.ps1 for '$Name' (slot $Slot)",
        "keycloak_url           = `"http://localhost:$($p.KEYCLOAK_PORT)`"",
        "edge_url               = `"http://localhost:$($p.EDGE_HTTP_PORT)`"",
        "vite_dev_url           = `"http://localhost:$($p.VITE_PORT)`"",
        "azurite_blob_endpoint  = `"http://127.0.0.1:$($p.AZURITE_BLOB_PORT)/devstoreaccount1`"",
        "azurite_queue_endpoint = `"http://127.0.0.1:$($p.AZURITE_QUEUE_PORT)/devstoreaccount1`"",
        "mssql_container        = `"freedom-$Name-mssql`"",
        "wiremock_port          = $($p.WIREMOCK_PORT)",
        "grafana_port           = $($p.GRAFANA_PORT)",
        "mailpit_port           = $($p.MAILPIT_UI_PORT)",
        "edge_dashboard_port    = $($p.EDGE_DASHBOARD_PORT)"
    )
}

function Get-AgentTestVariables {
    param(
        [Parameter(Mandatory)][int]$Slot,
        [Parameter(Mandatory)][hashtable]$Passwords,
        [string]$HostName = 'localhost',
        [string]$StorageHost = '127.0.0.1',
        [bool]$RequireIntegration = $true
    )

    $p = Get-AgentPorts -Slot $Slot
    $sql = { param($user, $pw) "Server=$HostName,$($p.MSSQL_PORT);Database=Freedom;User Id=$user;Password=$pw;TrustServerCertificate=True;Encrypt=False;Connect Timeout=3" }
    # An IP, never a hostname: on a non-default port the Azure SDK only treats an IP endpoint as
    # path-style, and otherwise drops the container from the blob URL (ContainerNotFound).
    $storage = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=$($script:AzuriteKey);" +
        "BlobEndpoint=http://$StorageHost`:$($p.AZURITE_BLOB_PORT)/devstoreaccount1;" +
        "QueueEndpoint=http://$StorageHost`:$($p.AZURITE_QUEUE_PORT)/devstoreaccount1;"

    $vars = [ordered]@{
        FREEDOM_BASE_URL                    = "http://${HostName}:$($p.EDGE_HTTP_PORT)"
        FREEDOM_OIDC_URL                    = "http://${HostName}:$($p.KEYCLOAK_PORT)/realms/freedom"
        PLAYWRIGHT_BASE_URL                 = "http://${HostName}:$($p.EDGE_HTTP_PORT)"
        VITE_API_PROXY_TARGET               = "http://${HostName}:$($p.EDGE_HTTP_PORT)"
        ConnectionStrings__Freedom          = & $sql 'freedom_app' $Passwords.App
        ConnectionStrings__FreedomSensitive = & $sql 'freedom_sensitive' $Passwords.Sensitive
        Storage__ConnectionString           = $storage
    }
    if ($RequireIntegration) { $vars['FREEDOM_REQUIRE_INTEGRATION'] = 'true' }
    $vars
}

function New-AgentTestEnv {
    param(
        [Parameter(Mandatory)][int]$Slot,
        [Parameter(Mandatory)][ValidateSet('powershell', 'sh')][string]$Shell,
        [Parameter(Mandatory)][hashtable]$Passwords,
        [string]$HostName = 'localhost',
        [string]$StorageHost = '127.0.0.1',
        [bool]$RequireIntegration = $true
    )

    $vars = Get-AgentTestVariables -Slot $Slot -Passwords $Passwords -HostName $HostName -StorageHost $StorageHost -RequireIntegration $RequireIntegration
    $header = "# generated by agent.ps1 (slot $Slot). Source it before dotnet test / playwright: " +
        $(if ($Shell -eq 'powershell') { '. ./.agent/env.ps1' } else { '. ./.agent/env.sh' })

    $lines = foreach ($key in $vars.Keys) {
        $value = $vars[$key].Replace("'", $(if ($Shell -eq 'powershell') { "''" } else { "'\''" }))
        if ($Shell -eq 'powershell') { "`$env:$key = '$value'" } else { "export $key='$value'" }
    }
    @($header) + @($lines)
}

function Test-StackMemoryBudget {
    param(
        [Parameter(Mandatory)][long]$TotalBytes,
        [Parameter(Mandatory)][int]$RunningStacks
    )

    (($RunningStacks + 1) * $script:StackMemoryBytes) -le $TotalBytes
}

function New-AgentContainerTestEnv {
    param(
        [Parameter(Mandatory)][int]$Slot,
        [Parameter(Mandatory)][hashtable]$Passwords
    )

    $lines = New-AgentTestEnv -Slot $Slot -Shell sh -Passwords $Passwords -HostName 'host.docker.internal' -StorageHost '__HOST_IP__'
    $ipLine = "export FREEDOM_HOST_IP=`$(getent ahostsv4 host.docker.internal | awk 'NR==1 {print `$1}')"
    @($lines[0], $ipLine) + @($lines[1..($lines.Count - 1)] | ForEach-Object { $_.Replace('__HOST_IP__', "'`"`$FREEDOM_HOST_IP`"'") })
}

function Read-SlotRegistry {
    param([Parameter(Mandatory)][string]$Path)

    $registry = @{}
    if (-not (Test-Path $Path)) { return $registry }

    $raw = Get-Content $Path -Raw
    if ([string]::IsNullOrWhiteSpace($raw)) { return $registry }

    $parsed = $raw | ConvertFrom-Json -AsHashtable
    foreach ($name in $parsed.Keys) { $registry[$name] = $parsed[$name] }
    $registry
}

function Write-SlotRegistry {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][hashtable]$Registry
    )

    $Registry | ConvertTo-Json -Depth 5 | Set-Content -Path $Path -Encoding utf8
}

function Use-SlotRegistryLock {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][scriptblock]$Action
    )

    $lockPath = "$Path.lock"
    $stream = $null
    foreach ($attempt in 1..50) {
        try {
            $stream = [System.IO.File]::Open($lockPath, 'OpenOrCreate', 'ReadWrite', 'None')
            break
        } catch [System.IO.IOException] {
            Start-Sleep -Milliseconds 200
        }
    }
    if ($null -eq $stream) { throw "Could not lock $lockPath; is another agent.ps1 running?" }

    try { & $Action } finally { $stream.Dispose() }
}

function Test-PortFree {
    param([Parameter(Mandatory)][int]$Port)

    $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Any, $Port)
    try { $listener.Start(); $true } catch { $false } finally { $listener.Stop() }
}
